# Generated by Django 3.1.3 on 2020-11-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_verification',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Not verified')], default=False, verbose_name='Email verification:'),
        ),
    ]
