# Generated by Django 3.1.3 on 2020-11-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201121_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_verification',
            field=models.BooleanField(blank=True, choices=[(False, 'Not verified'), (True, 'Verified')], default=False, verbose_name='Email verification:'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
    ]
